#!/bin/bash

RED="$(tput setaf 1)"
GREEN="$(tput setaf 2)"
YELLOW="$(tput setaf 3)"
NC="$(tput sgr0)"
TICK="${GREEN}✓${NC}"
CROSS="${RED}✘${NC}"

if [ -z "$(which httrack)" ]; then
  sudo apt -y install httrack
  if [ $? != 0 ]; then
    echo "${RED}ERROR${NC}: Failed to install httrack"
    exit 1
  fi
fi

if [ ! -d /var/www ]; then
    echo "${RED}ERROR${NC}: No Apache directory at /var/www/. Please install Apache2"
    exit 1
fi
cd /var/www/

if [ ! -d /var/www/scripts ]; then
    echo "${RED}ERROR${NC}: No scripts repo in /var/www/scripts. Please git clone the office/scripts there"
    exit 1
fi

# ------------------------------------------------------------------- Web Frameworks
if [ -d wintercms.com ]; then
  cd wintercms.com
  httrack --continue
  cd ..
else
  echo "${GREEN}INFO${NC}: Mirroring wintercms.com documentation to ${YELLOW}http://wintercmsdocs.laptop${NC}"
  httrack https://wintercms.com/docs/v1.2/docs/ -O wintercms.com
fi
cd wintercms.com
sudo ../scripts/acorn-setup-hostname wintercmsdocs
cd -

if [ ! -d developer.wordpress.org ]; then
  cd developer.wordpress.org
  httrack --continue
  cd ..
else
  echo "${GREEN}INFO${NC}: Mirroring developer.wordpress.org documentation to ${YELLOW}http://wordpressdeveloper.laptop${NC}"
  httrack https://developer.wordpress.org -O developer.wordpress.org
fi
cd developer.wordpress.org
sudo ../scripts/acorn-setup-hostname wordpressdeveloper
cd -

if [ ! -d api.drupal.org ]; then
  cd api.drupal.org
  httrack --continue
  cd ..
else
  echo "${GREEN}INFO${NC}: Mirroring api.drupal.org documentation to ${YELLOW}http://drupalapi.laptop${NC}"
  httrack https://api.drupal.org -O api.drupal.org
fi
cd developer.wordpress.org
sudo ../scripts/acorn-setup-hostname drupalapi
cd -

if [ ! -d api.jquery.com ]; then
  cd api.jquery.com
  httrack --continue
  cd ..
else
  echo "${GREEN}INFO${NC}: Mirroring api.jquery.com documentation to ${YELLOW}http://api.jquery.laptop${NC}"
  httrack https://api.jquery.com/ -O api.jquery.com
fi
cd api.jquery.com
sudo ../scripts/acorn-setup-hostname jquery
cd -

# ------------------------------------------------------------------- Infrastructure
if [ ! -d www.postgresql.org ]; then
  cd www.postgresql.org
  httrack --continue
  cd ..
else
  echo "${GREEN}INFO${NC}: Mirroring postgresql.org documentation to ${YELLOW}http://postgresqldocs.laptop${NC}"
  httrack https://www.postgresql.org/docs/16/ -O www.postgresql.org
fi
cd www.postgresql.org
sudo ../scripts/acorn-setup-hostname postgresqldocs
cd -

if [ ! -d www.gnu.org ]; then
  cd www.gnu.org
  httrack --continue
  cd ..
else
  echo "${GREEN}INFO${NC}: Mirroring Gnu bash documentation to ${YELLOW}http://bashdocs.laptop${NC}"
  httrack https://www.gnu.org/software/bash/manual/html_node/ -O www.gnu.org
fi
cd www.gnu.org
sudo ../scripts/acorn-setup-hostname bashdocs
cd -

if [ ! -d www.php.net ]; then
  cd www.php.net
  httrack --continue
  cd ..
else
  echo "${GREEN}INFO${NC}: Mirroring PHP documentation to ${YELLOW}http://php.laptop${NC}"
  httrack https://www.php.net/manual/en/ -O www.php.net
fi
cd www.php.net
sudo ../scripts/acorn-setup-hostname php
cd -
