#!/bin/bash

RED="$(tput setaf 1)"
GREEN="$(tput setaf 2)"
YELLOW="$(tput setaf 3)"
NC="$(tput sgr0)"
TICK="${GREEN}✓${NC}"
CROSS="${RED}✘${NC}"

# This script installs ALL Acorn plugins and runs the system
# It can be run from within an existing Laravel / Winter installation
# or to install the entire framework from scratch
run_dir=`pwd` # Bald
script_dir=`dirname $(realpath $0)`
script=`basename $0`
install_dir=/var/www
install_grp=www-data

name=$1
password=$2
db_port=$3
outeruser=$USER

# -------------------------------------------- Sanitise inputs
if [ "$(id -u)" == "0" ]; then
	echo "${RED}ERROR${NC}: Do not run this script as root"
	exit 1
fi
if [ ! -f $script_dir/acorn-setup-database ]; then
	echo "${RED}ERROR${NC}: acorn-setup-database required"
	exit 1
fi
if [ ! -f $script_dir/acorn-setup-hostname ]; then
	echo "${RED}ERROR${NC}: acorn-setup-database required"
	exit 1
fi
if [ -z "$name" ];     then
	echo "${RED}ERROR${NC}: name parameter required"
	exit 1
fi
if [ -z "$password" ]; then password="QueenPool1@"; fi
if [ -z "$db_port" ];  then db_port="5432"; fi

# -------------------------------------------- 3rd party installs
if [ -z "$(which php)" ]; then
	echo "${GREEN}INFO${NC}: Installing PHP"
	sudo apt install -y php php-pgsql
fi

if [ -z "$(which apache2ctl)" ]; then
	echo "${GREEN}INFO${NC}: Installing Apache"
	sudo apt install -y apache2
fi

if [ -z "$(which composer)" ]; then
	echo "${GREEN}INFO${NC}: Installing Composer v2.5.8"
	# https://getcomposer.org/download/
	# e21205b207c3ff031906575712edab6f13eb0b361f2085f1f1237b7126d785e826a450292b6cfd1d64d92e6563bbde02
	php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
	php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
	if [ -f composer-setup.php ]; then
		php composer-setup.php
		php -r "unlink('composer-setup.php');"
		sudo mv composer.phar /usr/local/bin/composer
	else
		echo "${RED}ERROR${NC}: Composer setup not found. Has the version been upgraded? New hash?"
		exit 1
	fi
fi
if [ "$(composer --version | cut -d " " -f 3  | cut -d "." -f 1)" -lt 2 ]; then
	echo "${RED}ERROR${NC}: Composer >= v2.5.8 required"
	exit 1
fi

if [ -z "$(which psql)" ]; then
	sudo apt install -y postgresql postgresql-contrib
fi
# Copied from Winter installation guide
sudo apt install -y php php-curl php-xml php-gd php-json php-mbstring php-mysql php-sqlite3 php-zip
# sudo apt install -y php-ctype php-fileinfo

if [ -z "$(groups | grep $install_grp)" ]; then
	echo "${RED}ERROR${NC}: $outeruser was not in the Apache2 web-server group $install_grp, so you have been added to it now. Please log out and in again from your laptop and then run this $0 script again"
	sudo usermod -a -G $install_grp $outeruser
	exit 1
fi

# Work only in the standard install place
if [ ! -d $install_dir ]; then
	echo "${YELLOW}WARNING${NC}: $install_dir was not found, creating..."
	sudo mkdir -p $install_dir
fi
cd $install_dir
sudo chown $install_grp:$install_grp .; sudo chmod g+rw .

# -------------------------------------------- Website Installation
if [ -d $name ]; then
	if [ -z "$(ls $name)" ]; then
		echo "${YELLOW}WARNING${NC}: Directory [$name] already exists. Entering..."
	else
		read -p "${YELLOW}WARNING${NC}: Directory [$name] exists and is not empty. Continue? [Y/n] " yn
		case $yn in
			[Yy]* )
				;;
			* )
				echo "ok, exciting process. please resolve manually"
				exit 1;
				;;
		esac
	fi
	cd $name
else
	echo "${GREEN}INFO${NC}: Installing Winter into directory $(pwd)/${YELLOW}$name${NC}"
	# https://getcomposer.org/doc/03-cli.md#create-project
	# We have our own install procedures below, so we disable the standard scripts
	composer create-project wintercms/winter $name --no-scripts
	cd $name
	sudo chown -R $install_grp:$install_grp .; sudo chmod -R g+rw .
	sudo chmod +x artisan

	linecount_env=0
	if [ -f .env ]; then linecount_env=`wc -l .env | cut -d " " -f 1`; fi
	if [ $linecount_env -le 2 ]; then
		echo "${YELLOW}WARNING${NC}: Auto-populating> 2 the .env file"
		echo "APP_NAME=intranet
APP_DEBUG=true
APP_URL='http://$hostname'

# PostgreSQL only
DB_CONNECTION='pgsql'
DB_HOST='127.0.0.1'
DB_PORT=$db_port
DB_DATABASE='$name'
DB_USERNAME='$name'
DB_PASSWORD='$password'

CACHE_DRIVER='file'
SESSION_DRIVER='file'
QUEUE_CONNECTION='sync'

# Default logging email setup
MAIL_MAILER=log
MAIL_LOG_CHANNEL=null
MAIL_HOST=null
MAIL_PORT=null
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=noreply@example.com
MAIL_FROM_NAME="${APP_NAME}"

# Example SMTP setup. Set the username in your account
# MAIL_MAILER='smtp'
# MAIL_ENCRYPTION='tls'
# MAIL_HOST='smtp.stackmail.com'
# MAIL_PASSWORD=null
# MAIL_PORT=465
# MAIL_USERNAME=null

ROUTES_CACHE=false
ASSET_CACHE=false
LINK_POLICY='detect'
ENABLE_CSRF=true
DATABASE_TEMPLATES=false
" >> .env
	fi

	# This will also update the Laravel .env file to use the created database
	$script_dir/acorn-setup-database pgsql $name
	# This will also update the Laravel .env file to use the hostname (.laptop)
	sudo $script_dir/acorn-setup-hostname $name
fi
hostname=$name.laptop

# Initial installation
# We could also use ./artisan winter:install --no-interaction
echo "${GREEN}INFO${NC}: composer install"
composer install
echo "${GREEN}INFO${NC}: artisan migrate"
php artisan migrate
if [ "$?" != 0 ]; then
	echo "${RED}ERROR${NC}: Migration failed, exiting"
	exit 0
fi
php artisan key:generate

# -------------------------------------------- Install 3rd party modules
echo "${GREEN}INFO${NC}: composer require 3rd party vendor modules"
# IMAP & SMTP
if [ ! -d vendor/webklex/php-imap ];     then composer require webklex/php-imap;     fi
if [ ! -d vendor/webklex/laravel-imap ]; then composer require webklex/laravel-imap; fi
sed -i "s|MAIL_HOST=\".*\"|MAIL_HOST=\"smtp.stackmail.com\"|" .env
sed -i "s|MAIL_PORT=\".*\"|MAIL_PORT=465|" .env

# QR Codes are supported in core now
if [ ! -d vendor/simplesoftwareio/simple-qrcode ]; then composer require simplesoftwareio/simple-qrcode; fi

# Copy Kurdish system and backend lang.php files in to place
cp -r $script_dir/winter/system/lang/ku modules/system/lang
if [ "$?" != 0 ]; then echo "${RED}ERROR${NC}: Failed to install system module ku\lang.php"; exit 1; fi
cp -r $script_dir/winter/backend/lang/ku modules/system/lang
if [ "$?" != 0 ]; then echo "${RED}ERROR${NC}: Failed to install backend module ku\lang.php"; exit 1; fi
composer require winter/wn-translate-plugin
if [ "$?" != 0 ]; then echo "${RED}ERROR${NC}: Failed to install package"; exit 1; fi
composer require winter/wn-location-plugin
if [ "$?" != 0 ]; then echo "${RED}ERROR${NC}: Failed to install package"; exit 1; fi
composer require winter/wn-tailwindui-plugin # Menus
if [ "$?" != 0 ]; then echo "${RED}ERROR${NC}: Failed to install package"; exit 1; fi
composer require staudenmeir/eloquent-has-many-deep # New Deep relations
if [ "$?" != 0 ]; then echo "${RED}ERROR${NC}: Failed to install package"; exit 1; fi

# We use acorn-create-system usually, so no builder
# composer require winter/wn-builder-plugin
# if [ "$?" != 0 ]; then echo "${RED}ERROR${NC}: Failed to install package"; exit 1; fi

# Temporary hack until we work out how to auto generate the classes.php
if [ -f $script_dir/winter/classes.php ]; then
	echo "${YELLOW}WARNING${NC}: Temporary hack to generate ~/storage/framework/classes.php"
	cp $script_dir/winter/classes.php storage/framework/;
fi

# -------------------------------------------- Install AA modules and plugins
echo "${GREEN}INFO${NC}: composer require AA modules (from AA gitlab)"
read -p "Install AA infrastructure (requires GitLab keys) [y|n]? (y) " yn
if [ "$yn" == 'y' ]; then
	cd modules
	if [ ! -d acorn ]; then
		git clone git@gitlab.acorn.org:office/acorn.git
		if [ "$?" != 0 ]; then
			echo "${RED}ERROR${NC}: Failed to checkout first office repository. Probably you do not have permissions. Please resolve and start again."
			exit 1
		fi
	fi
	if [ ! -d dbauth ]; then git clone git@gitlab.acorn.org:office/dbauth.git;  fi
	cd ..

	cd plugins
	mkdir -p acorn
	cd acorn

	if [ ! -d rtler ];     then
		git clone git@gitlab.acorn.org:office/rtler.git
		if [ "$?" != 0 ]; then echo "${RED}ERROR${NC}: Failed to checkout first office repository. Probably you do not have permissions. Please resolve and start again."; exit 1; fi
	fi
	if [ ! -d backendlocalization ];  then
		git clone git@gitlab.acorn.org:office/backendlocalization.git
		if [ "$?" != 0 ]; then echo "${RED}ERROR${NC}: Failed to install package"; exit 1; fi
	fi
	if [ ! -d user ];  then
		git clone git@gitlab.acorn.org:office/user.git
		if [ "$?" != 0 ]; then echo "${RED}ERROR${NC}: Failed to install package"; exit 1; fi
	fi
	if [ ! -d location ];  then
		git clone git@gitlab.acorn.org:office/location.git;
		if [ "$?" != 0 ]; then echo "${RED}ERROR${NC}: Failed to install package"; exit 1; fi
	fi
	if [ ! -d messaging ]; then
		git clone git@gitlab.acorn.org:office/messaging.git;
		if [ "$?" != 0 ]; then echo "${RED}ERROR${NC}: Failed to install package"; exit 1; fi
	fi
	if [ ! -d calendar ];  then
		git clone git@gitlab.acorn.org:office/calendar.git;
		if [ "$?" != 0 ]; then echo "${RED}ERROR${NC}: Failed to install package"; exit 1; fi
	fi
	cd ../..
	# TODO: Generate /storage/framework/classes.php because we have installed via git, not composer
	# php artisan package:discover or maybe
	# php artisan plugin:refresh location
	# php artisan plugin:refresh messaging
	# php artisan plugin:refresh calendar
	# TODO: The hack way above which copies a pre-written classes.php works for now...

	# patches
	echo "${GREEN}INFO${NC}: Patches"
	# TODO: The tailwind patch will not work because app.js is now minified
	# service-providers.php patch will add the service providers in the correct order
	if [ -f $script_dir/acorn-apply-patch-directory ] && [ -d $script_dir/winter ]; then
		$script_dir/acorn-apply-patch-directory "$script_dir/winter"
	fi

	if [ -f $script_dir/acorn-add-websockets ]; then
		$script_dir/acorn-add-websockets
	fi
fi

# To generate /storage/framework/packages.php
php artisan package:discover

# Migrate our new plugins / modules
echo "${GREEN}INFO${NC}: Final artisan migrate"
php artisan migrate
if [ "$?" != 0 ]; then
	echo "${RED}ERROR${NC}: Migration failed, exiting"
	exit 0
fi

# -------------------------------------------- Admin
if [ -d ../scripts ]; then
	echo "${GREEN}INFO${NC}: Linking ${YELLOW}acorn-*${NC} scripts"
	for script in ../scripts/acorn-git-* ../scripts/acorn-create-system ../scripts/acorn-winter-down-up ../scripts/acorn-winter-update-sqls; do
		script_name=`basename "$script"`
		if [ ! -f "$script_name" ]; then ln -s "$script" .; fi
	done
fi

php artisan winter:passwd -q admin password
if [ "$?" == 0 ]; then
	echo "${GREEN}INFO${NC}: ${YELLOW}admin${NC} password set to ${YELLOW}password${NC}"
else
	echo "${RED}ERROR${NC}: ${YELLOW}admin${NC} password not set because user not found"
fi

php artisan winter:passwd -q $name $password
if [ "$?" == 0 ]; then
	echo "${GREEN}INFO${NC}: ${YELLOW}$name${NC} password set to ${YELLOW}$password${NC}"
else
	echo "${YELLOW}WARNING${NC}: ${YELLOW}$name${NC} password not set because user not found"
fi

echo "${YELLOW}WARNING${NC}: DBAuth was installed but not enabled. This is because setup would not have been possible without continually entering the user/pass for all artisan operations. Change .env DB_USERNAME=<DBAUTH> to enable."
read -p "Enable now? [Y/n] " yn
case $yn in
	[Yy]* )
		# Set <DBAUTH> in .env
		sed -i 's/^DB_USERNAME=.*/DB_USERNAME=<DBAUTH>/' .env
		sed -i 's/^DB_PASSWORD=.*/DB_PASSWORD=<DBAUTH>/' .env
		echo "${GREEN}INFO${NC}: DBAuth enabled."

		echo "${GREEN}INFO${NC}: ARTISAN_AUTO_LOGIN & artisan user."
		echo "ARTISAN_AUTO_LOGIN=1" >> .env
		./artisan user:create-user -c -s artisan QueenPool1@

		echo "${GREEN}INFO${NC}: createsystem user."
		if [ -f acorn-create-system ]; then
			echo "${GREEN}INFO${NC}: Create ${YELLOW}create-system${NC}/${YELLOW}QueenPool1@${NC} superuser"
			./artisan user:create-user -c -s createsystem QueenPool1@
		fi
		;;
esac

# Create some AA & backend users with default setup
# These creates will trigger DBAuth if it is enabled
./artisan user:create-user -c -d -s admin QueenPool1@
./artisan user:create-user -c -d -s $outeruser QueenPool1@
./artisan user:create-user -c -d demo password

# Set the default backend timezone to +03:00
./artisan acorn:set-config cms.backendTimezone Europe/Istanbul

# -------------------------------------------- Security
# Note that our demons auto-run now
# courtesy of our AA module
echo "${GREEN}INFO${NC}: Resettings permissions"
sudo chown -R $install_grp:$install_grp .; sudo chmod -R g+rw .

echo "${GREEN}INFO${NC}: Login in to http://$name.laptop"

