#!/bin/bash

RED="$(tput setaf 1)"
GREEN="$(tput setaf 2)"
YELLOW="$(tput setaf 3)"
NC="$(tput sgr0)"
TICK="${GREEN}✓${NC}"
CROSS="${RED}✘${NC}"

if [ "$1" == "--help" ]; then
	echo "Usage: ./acorn-restore [postgresql-server-port]"
	echo "acorn-restore will check all *.backup, *.sql, *.tar.gz files and restore them to the appropriate place"
	echo "All filenames should match the target directories|databases"
	exit
fi

port=5432
if [ -n "$1" ]; then
	port=$1; 
elif [ -f .env ]; then
	port=`grep DB_PORT .env | cut -d '=' -f 2`
	if [ -n "$port" ]; then
		echo "Port $port selected from Laravel .env"
	fi
fi
version=`sudo -u postgres psql -p $port -d postgres -c "select version()" | head -n 3 | tail -n -1 | cut -d ' ' -f 3 | cut -d ' ' -f 3`

# ------------------------------------------------- DB .sql backups
# for backup_file in *.sql; do
# 	db=`echo "$backup_file" | cut -d '-' -f 1 | cut -d '.' -f 1`
# 	if [ -n "$backup_file" ]; then
# 		read -p "Restore ${GREEN}$backup_file${NC} into ${GREEN}$db${NC} server version [${GREEN}$version${NC}] (yn)? [y]" yn
# 		if [ "$yn" != 'n' ]; then
# 			sudo -u postgres psql -p $port -d "$db" -c "drop schema if exists public cascade; drop schema if exists product cascade; create schema public;"
# 			sudo -u postgres psql -p $port "$db" < "$backup_file"
# 		fi
# 	fi
# done

# ------------------------------------------------- DB .backup backups
for backup_file in *.backup; do
	db=`echo "$backup_file" | cut -d '-' -f 1 | cut -d '.' -f 1`
	if [ -n "$backup_file" ]; then
		read -p "Restore ${GREEN}$backup_file${NC} into ${GREEN}$db${NC} server version [${GREEN}$version${NC}] (yn)? [y]" yn
		if [ "$yn" != 'n' ]; then
			# TODO: Create missing logins: How can we know the password?
			# Schema and grants
			sudo -u postgres psql -p $port -d "$db" -c "drop schema if exists public cascade; drop schema if exists product cascade;"
			sudo -u postgres psql -p $port -d "$db" -c "create schema public;"
			sudo -u postgres psql -p $port -d "$db" -c "GRANT ALL ON SCHEMA public to PUBLIC;"
			# Main run
			sudo -u postgres pg_restore -p $port -d $db $backup_file
		fi
	fi
done

# ------------------------------------------------- Filesytem
for backup_file in *.tar.gz; do
	dir=`echo "$backup_file" | cut -d '-' -f 1 | cut -d '.' -f 1`
	if [ -n "$backup_file" ]; then
		read -p "Restore ${GREEN}$backup_file${NC} into /var/www/${GREEN}$dir${NC}/ (yn)? [y]" yn
		if [ "$yn" != 'n' ]; then
			sudo rm -rf /var/www/$dir
			sudo tar -xzf $backup_file -C /var/www/
			sudo chown -R www-data:www-data /var/www/$dir
			sudo chmod -R g+rw /var/www/$dir
		fi
	fi
done

# ------------------------------------------------- Config checks
env="/var/www/$dir/.env"
if [ -f "$env" ]; then
	if [ -n "$(grep -E ^APP_DEBUG=true $env)" ]; then
		read -p "Place system in to production mode (yn)? [y] " yn
		if [ "$yn" != 'n' ]; then
			sed -i 's/^APP_DEBUG=true/APP_DEBUG=false/' $env
		fi
	fi

	# Adjust APP_URL .laptop => https://... acorn.org
	if [ -n "$(grep $db\.laptop)" $env ]; then
		read -p "Adjust URL from http .laptop to https .acorn.org (yn)? [y] " yn
		if [ "$yn" != 'n' ]; then
			sed -i "s/$db\.laptop/$db.acorn.org/" $env
			sed -i 's|http://|https://|' $env
		fi
	fi
fi
