#!/bin/bash

RED="$(tput setaf 1)"
GREEN="$(tput setaf 2)"
YELLOW="$(tput setaf 3)"
NC="$(tput sgr0)"
TICK="${GREEN}✓${NC}"
CROSS="${RED}✘${NC}"

commit_message=$1

echo "## --------------------------------------------- ${GREEN}pre-run checks${NC}"
./acorn-git-all config --global --add safe.directory .
./acorn-git-all config pull.rebase false

echo "## --------------------------------------------- ${GREEN}git add${NC}"
./acorn-git-all add .

echo "## --------------------------------------------- ${GREEN}git commit${NC}"
if [ -z "$commit_message" ]; then
  read -p "Commit message? (no_message) " commit_message
  if [ -z "$commit_message" ]; then commit_message="no_message"; fi
fi
./acorn-git-all commit -m "'$commit_message'"

#echo "## --------------------------------------------- ${GREEN}git pull${NC}"
#./acorn-git-all pull

echo "## --------------------------------------------- ${GREEN}git push${NC}"
./acorn-git-all push
