#!/bin/bash

RED="$(tput setaf 1)"
GREEN="$(tput setaf 2)"
YELLOW="$(tput setaf 3)"
NC="$(tput sgr0)"
TICK="${GREEN}✓${NC}"
CROSS="${RED}✘${NC}"

share_name=$1
conf=/etc/samba/smb.conf
home=/home/$USER
if [ "$USER" == "root" ]; then home='/root'; fi
path=$home/$share_name

if [ -z "$share_name" ]; then
    share_name=SambaShare
fi

# sudo apt update
sudo apt install samba

mkdir -p $path
if [ -z "$(grep $share_name $conf)" ]; then
    echo "[$share_name]
    comment = Samba on Ubuntu
    path = $path
    read only = yes
    browsable = yes" | sudo tee -a $conf
    echo "[$share_name] for $path injected in to $conf"
else
    echo "[$share_name] already found in $conf"
fi

sudo ufw allow samba
sudo smbpasswd -a $USER
sudo systemctl restart smbd

