#!/bin/bash

RED="$(tput setaf 1)"
GREEN="$(tput setaf 2)"
YELLOW="$(tput setaf 3)"
NC="$(tput sgr0)"
TICK="${GREEN}✓${NC}"
CROSS="${RED}✘${NC}"

if [ -z "$(which httrack)" ]; then
  sudo apt -y install httrack
  if [ $? != 0 ]; then
    echo "${RED}ERROR${NC}: Failed to install httrack"
    exit 1
  fi
fi

if [ ! -d /var/www ]; then
    echo "${RED}ERROR${NC}: No Apache directory at /var/www/. Please install Apache2"
    exit 1
fi
cd /var/www/

if [ ! -d /var/www/scripts ]; then
    echo "${RED}ERROR${NC}: No scripts repo in /var/www/scripts. Please git clone the office/scripts there"
    exit 1
fi

if [ ! -d wintercms.com ]; then
  echo "${GREEN}INFO${NC}: Mirroring wintercms.com documentation to ${YELLOW}http://wintercmsdocs.laptop${NC}"
  httrack https://wintercms.com/docs/v1.2/docs/ -O wintercms.com
  cd wintercms.com
  sudo ../scripts/acorn-setup-hostname wintercmsdocs
  cd -
fi

if [ ! -d www.postgresql.org ]; then
  echo "${GREEN}INFO${NC}: Mirroring postgresql.org documentation to ${YELLOW}http://postgresqldocs.laptop${NC}"
  httrack https://www.postgresql.org/docs/16/ -O www.postgresql.org
  cd www.postgresql.org
  sudo ../scripts/acorn-setup-hostname postgresqldocs
  cd -
fi

if [ ! -d www.gnu.org ]; then
  echo "${GREEN}INFO${NC}: Mirroring Gnu bash documentation to ${YELLOW}http://bashdocs.laptop${NC}"
  httrack https://www.gnu.org/software/bash/manual/html_node/ -O www.gnu.org
  cd www.gnu.org
  sudo ../scripts/acorn-setup-hostname bashdocs
  cd -
fi

if [ ! -d www.php.net ]; then
  echo "${GREEN}INFO${NC}: Mirroring PHP documentation to ${YELLOW}http://php.laptop${NC}"
  httrack https://www.php.net/manual/en/ -O www.php.net
  cd www.php.net
  sudo ../scripts/acorn-setup-hostname php
  cd -
fi
