#!/usr/bin/bash
sudo systemctl stop apache2
sudo systemctl stop mysql
sudo systemctl stop postgresql
sudo systemctl stop mongod
sudo systemctl stop tomcat9
sudo systemctl stop php8.3-fpm
sudo systemctl stop snap.docker.dockerd
sudo systemctl stop clamav-freshclam
killall signal-desktop
sudo killall dotnet
sudo killall clamscan
